### ISSUE TITLE
Saving projects in Alpha 14 corrupts the project (FE13)

### ISSUE THREAD

**Issue by CryseArk** [thane98/paragon#58] opened 2020-11-15 04:18 UTC
Since switching to Alpha 14 I've noticed that project saving (for FE13 at least) is broken. The details I've managed to gather are as follows.

- I was able to easily re-create this issue by starting a new project and then editing something innocuous (in this case changing the range of bronze bows to 2-3) and saving it. I seems anything that causes a GameData.bin.lz to appear in the project folder will cause this issue.  
-Using Alpha 14 to make a  change to an existing project from previous versions of Paragon will also cause things to break upon next load.
- Upon closing paragon and launching it again in an attempt to load the project, your modules will be limited to data > Characters, Person and Renown, and face > Portraits / FaceData.
- Attempting to load something like the character module will either cause an error, or prompt you to open a file. The error reads "Unable to open module Characters". [paragon.log](https://github.com/thane98/paragon/files/5541841/paragon.log)
- While you cannot load an existing project, by making all the changes you want before saving for the first time and then loading the edited files with the game will actually cause the changes to take effect (Bow will appear as 2-3 range in this case), however there is one very odd occurrence. When loading a save from a chapter preparation screen, upon loading the save the chapter will immediately begin and skip the preparation screen entirely. I'm unsure of what would happen (if anything) if a save from the overworld was to be loaded.
- The issue occurs in all versions of Alpha 14, and disappears upon reverting to Alpha 13 hotfix, though unfortunately a project saved in Alpha 14 will still be broken when loaded and a new project must be created.

So I'm no programmer, but it seems like something about the way Alpha 14 saves projects breaks them, and it could have something to do with the preparation screen or overworld? Anyway, if there's any more information you need from me just let me know and I'll do my best to provide you with it.

**Comment by thane98** [comment] 2020-11-15 04:38
Sorry for any issues caused by this bug - this was actually reported earlier through a private channel, but I never added an issue for it here.

Thanks you for the steps on reproducing this. Several parts of Paragon are currently going through rewrites at the moment, so it may be a while before a fix for this is out. However, the next release will have a fix.

**Comment by CryseArk** [comment] 2020-11-15 06:14
No worries! It truthfully wasn't much of an issue. I fiddled with it for a while, but it was only to try and figure out as much as possible about the issue so I could send you my findings.

Awesome. I'll be patiently but eagerly awaiting the next release!

**Comment by thane98** [comment] 2021-04-03 17:11
Should be resolved with rewrite alpha 1-3 or later.

**Closed by thane98** 2021-04-03 17:11 UTC
